// 12 guided stories (story-01..story-12)
// Cards reference existing content IDs; narration is per-card guidance.
import { base, SRC } from "./common.mjs";

const R = "original-illustration-needed";

function C(order, kind, content_id, narration) {
  return { order, kind, content_id, narration };
}

export const stories = [
  base("story-01", "Abraham: el viaje de la promesa", {
    type: "story",
    summary: "De Ur a Canaán: el llamado, el pacto y la fe del primer patriarca, en el mundo real del segundo milenio a. C.",
    eras: ["era-01"],
    duration_minutes: 5,
    cards: [
      C(1, "event", "evt-001", "Todo comienza con una partida: el texto bíblico presenta a Abraham dejando Ur por un llamado. ¿Qué sabemos de esa ciudad?"),
      C(2, "event", "evt-007", "Ur no es un lugar mítico: fue una metrópoli sumeria real, excavada y documentada. Este es el mundo del que parte Abraham."),
      C(3, "map", "map-01", "Sigue la ruta tradicional: más de mil kilómetros de Ur a Canaán pasando por Harán. Recuerda: el itinerario es reconstruido."),
      C(4, "event", "evt-002", "En Canaán llega el pacto: descendencia y tierra. Los pactos sellados con ritos eran el lenguaje diplomático de la época."),
      C(5, "event", "evt-008", "Mientras tanto, en Babilonia, Hammurabi grababa sus leyes en piedra: el mundo legal que rodeaba a los patriarcas."),
      C(6, "quiz", "quiz-001", "Comprueba lo aprendido: ¿qué ciudad sumeria dejó Abraham según el relato?"),
    ],
    certainty: "disputed", confidence: "medium",
    sources: [SRC.RVR09, SRC.AYBD, SRC.BRITISH_MUSEUM],
    image_rights: R, tier: "free",
  }),
  base("story-02", "El Éxodo en diez minutos", {
    type: "story",
    summary: "Plagas, Pascua, mar abierto y Sinaí: el relato fundacional de Israel y lo que la historia puede decir de él.",
    eras: ["era-02"],
    duration_minutes: 6,
    cards: [
      C(1, "event", "evt-014", "Moisés, entre Egipto y Madián, recibe el llamado ante la zarza. La fecha del Éxodo es uno de los grandes debates."),
      C(2, "event", "evt-015", "Las diez plagas: el texto las presenta como confrontación con los dioses de Egipto."),
      C(3, "event", "evt-016", "La Pascua y la salida: la fiesta que Israel sigue celebrando como memorial de la liberación."),
      C(4, "event", "evt-017", "El cruce del mar de los Juncos: el hebreo no dice 'mar Rojo'. La localización exacta se debate."),
      C(5, "map", "map-02", "Dos hipótesis, un mapa: compara la ruta norte y la ruta sur. Ambas están marcadas como debatidas."),
      C(6, "event", "evt-018", "El Sinaí y los Diez Mandamientos: el pacto que constituye a Israel como pueblo."),
      C(7, "evidence", "evid-001", "La evidencia externa más antigua del nombre 'Israel': la estela de Merneptah, del 1207 a. C."),
      C(8, "quiz", "quiz-010", "Pon a prueba tu cronología: ordena los momentos del Éxodo."),
    ],
    certainty: "disputed", confidence: "medium",
    sources: [SRC.RVR09, SRC.AYBD, SRC.EGIPCIO_CAIRO],
    image_rights: R, tier: "free",
  }),
  base("story-03", "David: de pastor a rey", {
    type: "story",
    summary: "El gigante, la corona y el pacto: el ascenso del rey que dio nombre a una dinastía confirmada por la arqueología.",
    eras: ["era-03"],
    duration_minutes: 7,
    cards: [
      C(1, "event", "evt-028", "El valle de Elah: un joven pastor frente al campeón filisteo. La honda era un arma militar real."),
      C(2, "event", "evt-027", "Antes de David estuvo Saúl, el primer rey: ungido ante la presión filistea y caído en Gilboa."),
      C(3, "event", "evt-029", "La toma de Jerusalén: David convierte una fortaleza jebusea en capital neutral del reino unido."),
      C(4, "event", "evt-030", "El pacto davídico: la promesa de una dinastía perpetua, base de la esperanza mesiánica."),
      C(5, "evidence", "evid-006", "La prueba externa: la estela de Tel Dan menciona la 'casa de David' un siglo después."),
      C(6, "map", "map-04", "Recorre el ascenso: de Belén a Hebrón y a Jerusalén, con las campañas al este del Jordán."),
      C(7, "quiz", "quiz-020", "¿Qué confirma la estela de Tel Dan y qué no demuestra?"),
    ],
    certainty: "disputed", confidence: "medium",
    sources: [SRC.RVR09, SRC.AYBD, SRC.MUSEO_ISRAEL],
    image_rights: R, tier: "premium",
  }),
  base("story-04", "Salomón y el primer Templo", {
    type: "story",
    summary: "Oro, cedro y sabiduría: la construcción del Templo de Jerusalén y el esplendor —y las grietas— del reino.",
    eras: ["era-03"],
    duration_minutes: 6,
    cards: [
      C(1, "event", "evt-031", "Siete años de obra con artesanos de Tiro: el Templo como centro religioso de Israel."),
      C(2, "event", "evt-036", "Los fenicios: sin la madera de cedro y los artesanos de Tiro, el Templo no se habría construido."),
      C(3, "event", "evt-032", "La reina de Sabá: diplomacia de prestigio en la ruta del incienso."),
      C(4, "event", "evt-040", "El final del esplendor: la división del reino tras la muerte de Salomón."),
      C(5, "quiz", "quiz-025", "Comprueba lo aprendido sobre Salomón y su mundo."),
    ],
    certainty: "disputed", confidence: "medium",
    sources: [SRC.RVR09, SRC.AYBD, SRC.LOUVRE],
    image_rights: R, tier: "premium",
  }),
  base("story-05", "Elías: fuego en el Carmelo", {
    type: "story",
    summary: "El profeta frente a los profetas de Baal: la gran confrontación religiosa del reino del norte.",
    eras: ["era-04"],
    duration_minutes: 5,
    cards: [
      C(1, "event", "evt-044", "El contexto: Acab, Jezabel y un Israel poderoso que coquetea con el baalismo fenicio."),
      C(2, "event", "evt-041", "El desafío del Carmelo: el fuego que decide quién es Dios."),
      C(3, "event", "evt-042", "Eliseo, su sucesor: la curación de Naamán anticipa la apertura a las naciones."),
      C(4, "evidence", "evid-030", "El poder militar de este Israel: la estela de Qarqar y los 2.000 carros de Acab."),
      C(5, "quiz", "quiz-030", "Elías, Eliseo y su mundo: pon a prueba lo aprendido."),
    ],
    certainty: "traditional", confidence: "medium",
    sources: [SRC.RVR09, SRC.AYBD, SRC.BRITISH_MUSEUM],
    image_rights: R, tier: "premium",
  }),
  base("story-06", "Asiria a las puertas: Ezequías y Senaquerib", {
    type: "story",
    summary: "El 701 a. C.: el imperio más temido del mundo sitia Jerusalén. Dos versiones, un desenlace: la ciudad sobrevive.",
    eras: ["era-04"],
    duration_minutes: 7,
    cards: [
      C(1, "map", "map-05", "El avance asirio: de Nínive a Samaria, Laquis y Jerusalén. Las campañas están documentadas."),
      C(2, "event", "evt-047", "El precedente: Samaria cayó en el 722 a. C. tras tres años de asedio. Judá quedó sola."),
      C(3, "event", "evt-049", "Ezequías se prepara: el túnel de Siloé lleva el agua dentro de las murallas."),
      C(4, "evidence", "evid-007", "La inscripción de Siloé: la voz de los excavadores, en hebreo antiguo."),
      C(5, "event", "evt-048", "El asedio del 701: el prisma de Senaquerib y el relato bíblico coinciden en lo esencial."),
      C(6, "evidence", "evid-008", "Los relieves de Laquis: la versión visual asiria de la campaña."),
      C(7, "quiz", "quiz-035", "¿Qué dicen las fuentes asirias y qué dice el texto bíblico?"),
    ],
    certainty: "consensus", confidence: "high",
    sources: [SRC.BRITISH_MUSEUM, SRC.RVR09, SRC.IAA],
    image_rights: R, tier: "premium",
  }),
  base("story-07", "Babilonia y el regreso", {
    type: "story",
    summary: "Del trauma del 586 a la esperanza del retorno: el exilio que reinventó la fe de Israel.",
    eras: ["era-05"],
    duration_minutes: 8,
    cards: [
      C(1, "event", "evt-054", "El 586 a. C.: cae Jerusalén y arde el Templo. El trauma fundacional del judaísmo."),
      C(2, "evidence", "evid-017", "Las cartas de Laquis: la voz de los soldados en los últimos meses del reino."),
      C(3, "event", "evt-056", "Ezequiel junto al Quebar: visiones de huesos secos para un pueblo desterrado."),
      C(4, "map", "map-06", "El camino del destierro y del regreso: de Jerusalén a Babilonia por el Éufrates."),
      C(5, "event", "evt-059", "Ciro toma Babilonia: el cilindro que proclama tolerancia imperial."),
      C(6, "evidence", "evid-005", "El Cilindro de Ciro en el Museo Británico: el contexto del edicto de retorno."),
      C(7, "event", "evt-060", "El edicto y el regreso: no todos vuelven; la diáspora seguirá siendo numerosa."),
      C(8, "quiz", "quiz-040", "El exilio en fechas y objetos: comprueba lo aprendido."),
    ],
    certainty: "consensus", confidence: "high",
    sources: [SRC.BRITISH_MUSEUM, SRC.RVR09, SRC.OUP],
    image_rights: R, tier: "premium",
  }),
  base("story-08", "Nehemías: muros en 52 días", {
    type: "story",
    summary: "El copero del rey persa que reconstruyó Jerusalén: memorias en primera persona de una hazaña administrativa.",
    eras: ["era-05"],
    duration_minutes: 5,
    cards: [
      C(1, "event", "evt-064", "Nehemías obtiene permiso de Artajerjes y organiza la obra por turnos y familias."),
      C(2, "event", "evt-063", "Esdras y la lectura de la Ley: la escena fundacional de la lectura pública de las Escrituras."),
      C(3, "evidence", "evid-025", "Mientras tanto, en Egipto: los papiros de Elefantina muestran otro judaísmo, con templo propio."),
      C(4, "quiz", "quiz-045", "Nehemías y Esdras: fechas y debates."),
    ],
    certainty: "traditional", confidence: "medium",
    sources: [SRC.RVR09, SRC.AYBD, SRC.EGIPCIO_BERLIN],
    image_rights: R, tier: "premium",
  }),
  base("story-09", "Jesús en Galilea", {
    type: "story",
    summary: "Parábolas, lago y multitudes: tres años que cambiaron la historia, en la Galilea real del siglo I.",
    eras: ["era-06"],
    duration_minutes: 7,
    cards: [
      C(1, "map", "map-07", "El escenario: Galilea bajo Antipas, Judea bajo Roma. Ubica cada lugar antes de empezar."),
      C(2, "event", "evt-072", "El precursor: Juan el Bautista, confirmado por el historiador Josefo."),
      C(3, "event", "evt-073", "El ministerio galileo: Cafarnaúm como base, el lago como escenario."),
      C(4, "map", "map-08", "Sigue el itinerario: de Nazaret a Cesarea de Filipo y de vuelta al lago."),
      C(5, "evidence", "evid-021", "El contexto romano: la inscripción de Pilato en Cesarea."),
      C(6, "quiz", "quiz-050", "Galilea en el siglo I: comprueba lo aprendido."),
    ],
    certainty: "traditional", confidence: "medium",
    sources: [SRC.RVR09, SRC.IAA, SRC.AYBD],
    image_rights: R, tier: "premium",
  }),
  base("story-10", "La última semana en Jerusalén", {
    type: "story",
    summary: "De la entrada triunfal a la tumba vacía: siete días en la Jerusalén de la Pascua, con decenas de miles de peregrinos.",
    eras: ["era-06"],
    duration_minutes: 6,
    cards: [
      C(1, "event", "evt-075", "La entrada, el Templo, la cena y Getsemaní: la cronología difiere ligeramente entre evangelios."),
      C(2, "event", "evt-074", "El juez: quién fue Poncio Pilato según la inscripción de Cesarea y los historiadores."),
      C(3, "evidence", "evid-020", "El sumo sacerdote: el osario de Caifás y los límites de la identificación."),
      C(4, "event", "evt-076", "Crucifixión y resurrección: lo que la historia confirma y lo que pertenece a la fe."),
      C(5, "quiz", "quiz-055", "La última semana: historia y fuentes."),
    ],
    certainty: "traditional", confidence: "medium",
    sources: [SRC.RVR09, SRC.AYBD, SRC.MUSEO_ISRAEL],
    image_rights: R, tier: "premium",
  }),
  base("story-11", "Pablo: de perseguidor a viajero", {
    type: "story",
    summary: "El camino de Damasco y el primer viaje misionero: cómo un perseguidor se volvió el gran viajero del cristianismo.",
    eras: ["era-07"],
    duration_minutes: 7,
    cards: [
      C(1, "event", "evt-081", "La conversión: de Saulo el perseguidor a Pablo el apóstol."),
      C(2, "event", "evt-082", "El precedente: Pedro y Cornelio abren la puerta a los gentiles."),
      C(3, "map", "map-09", "El primer viaje: de Antioquía a Chipre y el interior de Anatolia, paso a paso."),
      C(4, "event", "evt-083", "El concilio de Jerusalén: la decisión que permitió un cristianismo sin circuncisión."),
      C(5, "quiz", "quiz-060", "Pablo misionero: comprueba lo aprendido."),
    ],
    certainty: "traditional", confidence: "medium",
    sources: [SRC.RVR09, SRC.AYBD, SRC.OUP],
    image_rights: R, tier: "premium",
  }),
  base("story-12", "De Jerusalén a Roma", {
    type: "story",
    summary: "La expansión imparable: Éfeso, Corinto, el naufragio en Malta y la llegada a la capital del imperio.",
    eras: ["era-07"],
    duration_minutes: 8,
    cards: [
      C(1, "event", "evt-085", "Éfeso: tres años en la tercera ciudad del imperio y el tumulto de Demetrio."),
      C(2, "evidence", "evid-022", "El anclaje cronológico: la inscripción de Galión fecha a Pablo en Corinto en el 51–52."),
      C(3, "event", "evt-088", "La carta a los Romanos: la exposición más influyente, escrita desde Corinto."),
      C(4, "map", "map-10", "El último tramo: tercer viaje, arresto, naufragio en Malta y llegada a Roma."),
      C(5, "event", "evt-086", "Prisionero rumbo a Roma: la apelación al César y Hechos 27."),
      C(6, "event", "evt-087", "El final de la era apostólica: Nerón y la primera persecución."),
      C(7, "quiz", "quiz-065", "De Jerusalén a Roma: el gran repaso."),
    ],
    certainty: "consensus", confidence: "high",
    sources: [SRC.RVR09, SRC.AYBD, SRC.DELFOS],
    image_rights: R, tier: "premium",
  }),
];
