/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as PaywallRouteImport } from './routes/paywall'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as TabsRouteImport } from './routes/tabs'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as EvidenceIdRouteImport } from './routes/evidence.$id'
import { Route as QuizIdRouteImport } from './routes/quiz.$id'
import { Route as StoryIdRouteImport } from './routes/story.$id'
import { Route as TabsIndexRouteImport } from './routes/tabs/index'
import { Route as TabsAprendeRouteImport } from './routes/tabs/aprende'
import { Route as TabsCronologiaRouteImport } from './routes/tabs/cronologia'
import { Route as TabsDescubrirRouteImport } from './routes/tabs/descubrir'
import { Route as TabsMapasRouteImport } from './routes/tabs/mapas'
import { Route as TabsPerfilRouteImport } from './routes/tabs/perfil'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const PaywallRoute = PaywallRouteImport.update({
  id: '/paywall',
  path: '/paywall',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const TabsRoute = TabsRouteImport.update({
  id: '/tabs',
  path: '/tabs',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const EvidenceIdRoute = EvidenceIdRouteImport.update({
  id: '/evidence/$id',
  path: '/evidence/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizIdRoute = QuizIdRouteImport.update({
  id: '/quiz/$id',
  path: '/quiz/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const StoryIdRoute = StoryIdRouteImport.update({
  id: '/story/$id',
  path: '/story/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const TabsIndexRoute = TabsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TabsRoute,
} as any)
const TabsAprendeRoute = TabsAprendeRouteImport.update({
  id: '/aprende',
  path: '/aprende',
  getParentRoute: () => TabsRoute,
} as any)
const TabsCronologiaRoute = TabsCronologiaRouteImport.update({
  id: '/cronologia',
  path: '/cronologia',
  getParentRoute: () => TabsRoute,
} as any)
const TabsDescubrirRoute = TabsDescubrirRouteImport.update({
  id: '/descubrir',
  path: '/descubrir',
  getParentRoute: () => TabsRoute,
} as any)
const TabsMapasRoute = TabsMapasRouteImport.update({
  id: '/mapas',
  path: '/mapas',
  getParentRoute: () => TabsRoute,
} as any)
const TabsPerfilRoute = TabsPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => TabsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/paywall': typeof PaywallRoute
  '/privacy': typeof PrivacyRoute
  '/tabs': typeof TabsRouteWithChildren
  '/terms': typeof TermsRoute
  '/evidence/$id': typeof EvidenceIdRoute
  '/quiz/$id': typeof QuizIdRoute
  '/story/$id': typeof StoryIdRoute
  '/tabs/aprende': typeof TabsAprendeRoute
  '/tabs/cronologia': typeof TabsCronologiaRoute
  '/tabs/descubrir': typeof TabsDescubrirRoute
  '/tabs/mapas': typeof TabsMapasRoute
  '/tabs/perfil': typeof TabsPerfilRoute
  '/tabs/': typeof TabsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/paywall': typeof PaywallRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/evidence/$id': typeof EvidenceIdRoute
  '/quiz/$id': typeof QuizIdRoute
  '/story/$id': typeof StoryIdRoute
  '/tabs/aprende': typeof TabsAprendeRoute
  '/tabs/cronologia': typeof TabsCronologiaRoute
  '/tabs/descubrir': typeof TabsDescubrirRoute
  '/tabs/mapas': typeof TabsMapasRoute
  '/tabs/perfil': typeof TabsPerfilRoute
  '/tabs': typeof TabsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/paywall': typeof PaywallRoute
  '/privacy': typeof PrivacyRoute
  '/tabs': typeof TabsRouteWithChildren
  '/terms': typeof TermsRoute
  '/evidence/$id': typeof EvidenceIdRoute
  '/quiz/$id': typeof QuizIdRoute
  '/story/$id': typeof StoryIdRoute
  '/tabs/aprende': typeof TabsAprendeRoute
  '/tabs/cronologia': typeof TabsCronologiaRoute
  '/tabs/descubrir': typeof TabsDescubrirRoute
  '/tabs/mapas': typeof TabsMapasRoute
  '/tabs/perfil': typeof TabsPerfilRoute
  '/tabs/': typeof TabsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/onboarding'
    | '/paywall'
    | '/privacy'
    | '/tabs'
    | '/terms'
    | '/evidence/$id'
    | '/quiz/$id'
    | '/story/$id'
    | '/tabs/aprende'
    | '/tabs/cronologia'
    | '/tabs/descubrir'
    | '/tabs/mapas'
    | '/tabs/perfil'
    | '/tabs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/onboarding'
    | '/paywall'
    | '/privacy'
    | '/terms'
    | '/evidence/$id'
    | '/quiz/$id'
    | '/story/$id'
    | '/tabs/aprende'
    | '/tabs/cronologia'
    | '/tabs/descubrir'
    | '/tabs/mapas'
    | '/tabs/perfil'
    | '/tabs'
  id:
    | '__root__'
    | '/'
    | '/onboarding'
    | '/paywall'
    | '/privacy'
    | '/tabs'
    | '/terms'
    | '/evidence/$id'
    | '/quiz/$id'
    | '/story/$id'
    | '/tabs/aprende'
    | '/tabs/cronologia'
    | '/tabs/descubrir'
    | '/tabs/mapas'
    | '/tabs/perfil'
    | '/tabs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OnboardingRoute: typeof OnboardingRoute
  PaywallRoute: typeof PaywallRoute
  PrivacyRoute: typeof PrivacyRoute
  TabsRoute: typeof TabsRouteWithChildren
  TermsRoute: typeof TermsRoute
  EvidenceIdRoute: typeof EvidenceIdRoute
  QuizIdRoute: typeof QuizIdRoute
  StoryIdRoute: typeof StoryIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paywall': {
      id: '/paywall'
      path: '/paywall'
      fullPath: '/paywall'
      preLoaderRoute: typeof PaywallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tabs': {
      id: '/tabs'
      path: '/tabs'
      fullPath: '/tabs'
      preLoaderRoute: typeof TabsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evidence/$id': {
      id: '/evidence/$id'
      path: '/evidence/$id'
      fullPath: '/evidence/$id'
      preLoaderRoute: typeof EvidenceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/$id': {
      id: '/quiz/$id'
      path: '/quiz/$id'
      fullPath: '/quiz/$id'
      preLoaderRoute: typeof QuizIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/story/$id': {
      id: '/story/$id'
      path: '/story/$id'
      fullPath: '/story/$id'
      preLoaderRoute: typeof StoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tabs/': {
      id: '/tabs/'
      path: '/'
      fullPath: '/tabs/'
      preLoaderRoute: typeof TabsIndexRouteImport
      parentRoute: typeof TabsRoute
    }
    '/tabs/aprende': {
      id: '/tabs/aprende'
      path: '/aprende'
      fullPath: '/tabs/aprende'
      preLoaderRoute: typeof TabsAprendeRouteImport
      parentRoute: typeof TabsRoute
    }
    '/tabs/cronologia': {
      id: '/tabs/cronologia'
      path: '/cronologia'
      fullPath: '/tabs/cronologia'
      preLoaderRoute: typeof TabsCronologiaRouteImport
      parentRoute: typeof TabsRoute
    }
    '/tabs/descubrir': {
      id: '/tabs/descubrir'
      path: '/descubrir'
      fullPath: '/tabs/descubrir'
      preLoaderRoute: typeof TabsDescubrirRouteImport
      parentRoute: typeof TabsRoute
    }
    '/tabs/mapas': {
      id: '/tabs/mapas'
      path: '/mapas'
      fullPath: '/tabs/mapas'
      preLoaderRoute: typeof TabsMapasRouteImport
      parentRoute: typeof TabsRoute
    }
    '/tabs/perfil': {
      id: '/tabs/perfil'
      path: '/perfil'
      fullPath: '/tabs/perfil'
      preLoaderRoute: typeof TabsPerfilRouteImport
      parentRoute: typeof TabsRoute
    }
  }
}

interface TabsRouteChildren {
  TabsAprendeRoute: typeof TabsAprendeRoute
  TabsCronologiaRoute: typeof TabsCronologiaRoute
  TabsDescubrirRoute: typeof TabsDescubrirRoute
  TabsMapasRoute: typeof TabsMapasRoute
  TabsPerfilRoute: typeof TabsPerfilRoute
  TabsIndexRoute: typeof TabsIndexRoute
}

const TabsRouteChildren: TabsRouteChildren = {
  TabsAprendeRoute: TabsAprendeRoute,
  TabsCronologiaRoute: TabsCronologiaRoute,
  TabsDescubrirRoute: TabsDescubrirRoute,
  TabsMapasRoute: TabsMapasRoute,
  TabsPerfilRoute: TabsPerfilRoute,
  TabsIndexRoute: TabsIndexRoute,
}

const TabsRouteWithChildren = TabsRoute._addFileChildren(TabsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OnboardingRoute: OnboardingRoute,
  PaywallRoute: PaywallRoute,
  PrivacyRoute: PrivacyRoute,
  TabsRoute: TabsRouteWithChildren,
  TermsRoute: TermsRoute,
  EvidenceIdRoute: EvidenceIdRoute,
  QuizIdRoute: QuizIdRoute,
  StoryIdRoute: StoryIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
